name: Python Auto run

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gazpacho pandas

      - name: Ensure List directory exists
        run: mkdir -p List

      - name: Run Python script
        run: |
          python mal_scrapper.py

      - name: Check List directory contents
        run: |
          echo "Listing contents of List directory:"
          ls -l List

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: scraping-data
          path: List/
          retention-days: 7