name: Python Anime Scraper

on:
  schedule:
    - cron: "0 5 * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gazpacho pandas

<<<<<<< HEAD
    - name: Run scraper
      run: |
        python mal_scrapper.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add List/
        git commit -m "Update anime rankings" || echo "No changes to commit"
        git push
=======
      - name: Python Auto run
        run: |
          python mal_scrapper.py
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: scraping-data
          path: List/
>>>>>>> parent of eb4f8ec (v3 to v4)
