name: Python Auto run

on:
  schedule:
    - cron: "0 5 * * *"  
  workflow_dispatch:

jobs:
  build:
    if: false # Quitar esta línea para activar el workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gazpacho pandas

      - name: Run Python script
        run: |
          python mal_scrapper.py

      - name: Run mean_score script
        run: |
          python mean_score.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add List/*.csv
          git add average_rank_per_anime.csv
          git commit -m "Added new ranking" || echo "No changes to commit"
          git push "https://${{ secrets.MATEO_TOKEN }}@github.com/TheMateo-ywh/mal_scrapper.git"