name: Python Auto run

on:
  schedule:
    - cron: "0 5 * * *"  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gazpacho pandas

      - name: Run Python script
        run: |
          python mal_scrapper.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: anime-rankings
          path: List/*.csv  # Only upload CSV files
          retention-days: 7